version: '3.3'
services:
  post_db:
    image: mongo:3.2
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
      - front_net

  ui:
    image: ${DOCKER_USERNAME}/ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      - front_net

  post:
    image: ${DOCKER_USERNAME}/post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - back_net
      - front_net

  comment:
    image: ${DOCKER_USERNAME}/comment
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
      - front_net

  # prometheus:
  #   image: ${DOCKER_USERNAME}/prometheus
  #   ports:
  #     - '9090:9090'
  #   volumes:
  #     - prometheus_data:/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'
  #     - '--storage.tsdb.retention=1d'
  #   networks:
  #     - back_net
  #     - front_net

  # node-exporter:
  #   image: prom/node-exporter:v0.15.2
  #   user: root
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.sysfs=/host/sys'
  #     - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
  #   networks:
  #     - back_net
  #     - front_net

  # mongo-exporter:
  #   image: forekshub/percona-mongodb-exporter:1.0.1
  #   environment:
  #     - MONGODB_URL=mongodb://post_db:27017
  #   networks:
  #     - back_net

  # blackbox-exporter:
  #   image: cloudprober/cloudprober:v0.10.9
  #   environment:
  #     - CLOUDPROBER_HOST=0.0.0.0
  #   volumes:
  #     - ./cloudprober.cfg:/etc/cloudprober.cfg
  #   ports:
  #     - '9313:9313'
  #   networks:
  #     - back_net
  #     - front_net

volumes:
  prometheus_data:
  post_db:

networks:
  back_net:
    ipam:
      config:
        - subnet: 10.0.4.0/24
  front_net:
    ipam:
      config:
        - subnet: 10.0.3.0/24
